import "./globals.css";

export const metadata = {
   title: "OpenSource-9 GAME",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="ko">
         <body>{children}</body>
      </html>
   );
}
